# Generated by Django 4.2.9 on 2025-11-03 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("coins_earned", models.PositiveIntegerField(default=0)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="coins_reward",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="max_score",
        ),
        migrations.AlterField(
            model_name="choice",
            name="text",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="QuizAttempt",
        ),
        migrations.AddField(
            model_name="attempt",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="lms.quiz",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
