# Generated by Django 4.2.9 on 2025-11-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_attempt_remove_quiz_coins_reward_remove_quiz_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="lms.course",
            ),
        ),
    ]
